name: test

on:
  pull_request:
    branches:
      - master
    types: [labeled]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: current branch
      run: |
        array = ${{ github.event.pull_request.labels }}
        echo "${array[*]}"
        
    - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"